# Generated by Django 4.2 on 2026-03-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='flower_color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('none', 'No flowers')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_habit',
            field=models.CharField(blank=True, choices=[('upright', 'Upright/Erect'), ('spreading', 'Spreading'), ('climbing', 'Climbing/Vining'), ('trailing', 'Trailing'), ('rosette', 'Rosette'), ('bushy', 'Bushy/Shrubby')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='has_fragrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='has_thorns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_succulent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='leaf_shape',
            field=models.CharField(blank=True, choices=[('oval', 'Oval'), ('heart', 'Heart-shaped'), ('elongated', 'Elongated/Lance'), ('lobed', 'Lobed'), ('compound', 'Compound/Divided'), ('needle', 'Needle-like')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small (0-30cm)'), ('medium', 'Medium (30cm-1m)'), ('large', 'Large (1m-3m)'), ('very_large', 'Very Large (3m+)')], default='medium', max_length=20, null=True),
        ),
    ]
